"""Standalone tester for cTrader Open API authentication using OpenApiPy."""
from __future__ import annotations

import json
from flask import Response
from src.app import app

# Correct import per Spotware docs:
# https://spotware.github.io/OpenApiPy/authentication/
from ctrader_open_api import Auth  # official SDK (Spotware / OpenApiPy)

CREDENTIALS_PATH = "data/ctrader.json"


def load_ctrader_credentials() -> dict[str, str]:
    with open(CREDENTIALS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@app.route("/auth-test", methods=["GET"])
def ctrader_auth_test() -> Response:
    """
    Generate and print an authorization URL using the official OpenApiPy Auth helper.
    Visit: http://localhost:8888/auth-test  → follow the 'url' it returns.
    """
    creds = load_ctrader_credentials()

    client_id = creds["client_id"]
    client_secret = creds["secret"]
    redirect_uri = "http://localhost:8888/redirect"

    # Initialize Auth helper (defaults to EndPoints.AUTH_URI → https://connect.spotware.com/apps/auth)
    auth = Auth(client_id, client_secret, redirect_uri)

    # Build the authorization URL via SDK (avoids path/env mistakes)
    auth_url = auth.getAuthUri()  # you can pass scope/baseUri if needed

    print("=== SDK generated authorization URL ===")
    print(auth_url)

    return (
        {
            "message": "Auth URL generated by OpenApiPy",
            "url": auth_url,
        },
        200,
    )


if __name__ == "__main__":
    # Run a minimal Flask server exposing /auth-test
    # Visit: http://localhost:8888/auth-test
    app.run(debug=True, host="0.0.0.0", port=8888)
